site_name: Slabserver | The Etho Community
site_url: https://slabserver.github.io
site_author: DaUltraMarine
site_description: >-
  Welcome to <b>Slabserver</b> – the heart of everything Etho. Founded in 2014, our community is a friendly, energetic, and inclusive space where fans of Etho can come to chat, connect, and create together.

# Home to all things Etho, Slabserver is a friendly, welcoming, and inclusive community for all fans.

theme:
  favicon: assets/images/favicon.png
  logo: assets/images/icon.png
  features:
    - navigation.tabs
  name: material
  custom_dir: overrides
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to Light Mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to Dark Mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to System Preference

markdown_extensions:
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- toc:
    permalink: true

# Page tree
nav:
  - Home: index.md
  # - Survival Multiplayer: smp/index.md
  - Slabserver SMP: smp/index.md
  - Documentation: documentation/index.md
  - Transparency Reports: transparency/index.md
  - History: history/index.md
  - Community Wiki: https://mediawiki.slabserver.org

extra_css:
  - assets/stylesheets/extra.css