site_name: Slabserver | The Etho Community
site_url: https://slabserver.github.io
site_author: DaUltraMarine
site_description: >-
  Welcome to <b>Slabserver</b> – the home of everything Etho. Founded in 2015, our community is a friendly, energetic, and inclusive space where fans of Etho can come to chat, connect, and create together.

theme:
  favicon: assets/images/favicon.png
  logo: assets/images/icon.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to Light Mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to Dark Mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to System Preference
plugins:
  - blog:
      blog_dir: transparency
      post_url_format: "{slug}"
      post_excerpt_separator: 
  - search

markdown_extensions:
- admonition
- attr_list
- md_in_html
- pymdownx.details     # used by adminitions
- pymdownx.superfences # used by adminitions
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true
    combine_header_slug: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- toc:
    permalink: true

# Page tree
nav:
  - Home: index.md
  - Documentation:
    - documentation/index.md
    - Minecraft Servers:
      - Client Macros: documentation/minecraft/client-macros.md
      - Client Mods: documentation/minecraft/client-mods.md
      - Server Plugins: documentation/minecraft/server-plugins.md
      - Clunkloader Guidelines: documentation/minecraft/chunkloaders.md
      - Shopping District Guidelines: documentation/minecraft/shopping-district.md
      # - Test Page Please Ignore: documentation/minecraft/a.md
    - General:
      - Gamenight Servers: documentation/general/gamenight-servers.md
      - Privacy Policy: documentation/general/privacy.md
  - Transparency Reports:
    - transparency/index.md
  - History: history/index.md
  - Community Wiki: https://wiki.slabserver.org

extra_css:
  - assets/stylesheets/extra.css