site_name: Slabserver Nexus
site_url: https://slabserver.github.io
theme:
  features:
    - navigation.tabs
  name: material
  custom_dir: overrides
  palette:

    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default 
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to system preference

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- toc:
    permalink: true

# Page tree
nav:
  - Home: index.md
  # - Survival Multiplayer: smp/index.md
  - Slabserver SMP: smp/index.md
  - Documentation: documentation/index.md
  - Transparency Reports: transparency/index.md
  - History: history/index.md
  - Community Wiki: https://mediawiki.slabserver.org